## Ansible managed
FROM pgvector/pgvector@sha256:d2ef61f42ef767baa5a1475393303cc235bcd92febd9d7014eddb48b41f3bad0

RUN apt-get update     && apt-get install -y --no-install-recommends pgbackrest     && rm -rf /var/lib/apt/lists/*     && mkdir -p /var/log/pgbackrest /var/lib/pgbackrest /var/spool/pgbackrest     && chown -R postgres:postgres /var/log/pgbackrest /var/lib/pgbackrest /var/spool/pgbackrest
